"""
Field extraction rules for the 23 MedPrime demo data points.

source_type assignment:
  doc-001 (Business Reg Certificate) -> "image"  (represents a scanned document)
  doc-002 (Pharmacist Cert)          -> "image"  (represents a scanned certificate)
  doc-003 (Supplier Contract)        -> "doc"    (text PDF)
  doc-004 (Price List)               -> "table"  (structured pricing table)
  doc-005 (ISO Certificate)          -> "doc"    (text PDF)
  doc-006 (Audited Accounts)         -> "table"  (financial statements with tables)
"""

from __future__ import annotations

DOC_SOURCE_TYPE: dict[str, str] = {
    "doc-001": "image",
    "doc-002": "image",
    "doc-003": "doc",
    "doc-004": "table",
    "doc-005": "doc",
    "doc-006": "table",
}

FIELD_RULES: list[dict] = [
    # Qualification
    {
        "id": "pt-001",
        "category": "Qualification",
        "label": "Business Registration No.",
        "doc_id": "doc-001",
        "doc_filename": "business_registration_certificate.pdf",
        "bm25_query": "68423917 Company Number",
        "extracted_value": "68423917",
        "expected_value": "68423917",
        "status": "verified",
        "fallback_box": {"x": 39.4, "y": 44.4, "width": 43.2, "height": 3.4},
    },
    {
        "id": "pt-002",
        "category": "Qualification",
        "label": "Company Name (English)",
        "doc_id": "doc-001",
        "doc_filename": "business_registration_certificate.pdf",
        "bm25_query": "MedPrime Healthcare Supplies Ltd",
        "extracted_value": "MedPrime Healthcare Supplies Ltd.",
        "expected_value": "MedPrime Healthcare Supplies Ltd.",
        "status": "verified",
        "fallback_box": {"x": 39.4, "y": 37.1, "width": 43.2, "height": 2.9},
    },
    {
        "id": "pt-003",
        "category": "Qualification",
        "label": "Company Name (Chinese)",
        "doc_id": "doc-001",
        "doc_filename": "business_registration_certificate.pdf",
        "bm25_query": "Yi Tai Yi Liao Yong Pin",
        "extracted_value": "醫泰醫療用品有限公司",
        "expected_value": "醫泰醫療用品有限公司",
        "status": "verified",
        "fallback_box": {"x": 39.4, "y": 40.0, "width": 43.2, "height": 4.5},
    },
    {
        "id": "pt-004",
        "category": "Qualification",
        "label": "Registered Address",
        "doc_id": "doc-001",
        "doc_filename": "business_registration_certificate.pdf",
        "bm25_query": "Cheung Tat Centre Tsing Yi Unit 8",
        "extracted_value": "Unit 7, 15/F, Kowloon Bay Industrial Ctr, 15 Wang Hoi Rd",
        "expected_value": "Unit 7, 15/F, Kowloon Bay Industrial Ctr, 15 Wang Hoi Rd",
        "status": "verified",
        "fallback_box": {"x": 39.4, "y": 54.5, "width": 43.2, "height": 2.7},
    },
    {
        "id": "pt-005",
        "category": "Qualification",
        "label": "Company Incorporation Date",
        "doc_id": "doc-001",
        "doc_filename": "business_registration_certificate.pdf",
        "bm25_query": "14 March 2012",
        "extracted_value": "2012-03-14",
        "expected_value": "2011-03-14",
        "status": "mismatch",
        "risk_note": "扫描件（图片）中识别到注册日期为 2012-03-14，但 KG 图谱中公司注册处记录为 2011-03-14。疑似文件替换或填写错误。",
        "fallback_box": {"x": 39.4, "y": 47.8, "width": 43.2, "height": 3.3},
    },
    {
        "id": "pt-006",
        "category": "Qualification",
        "label": "Responsible Pharmacist Name",
        "doc_id": "doc-002",
        "doc_filename": "pharmacist_qualification_cert.pdf",
        "bm25_query": "Chan Siu-Ming pharmacist responsible",
        "extracted_value": "Dr. Chan Siu-Ming, RPh",
        "expected_value": "Dr. Chan Siu-Ming, RPh",
        "status": "verified",
        "fallback_box": {"x": 20.0, "y": 22.0, "width": 42.0, "height": 4.0},
    },
    {
        "id": "pt-007",
        "category": "Qualification",
        "label": "Pharmacist Registration No.",
        "doc_id": "doc-002",
        "doc_filename": "pharmacist_qualification_cert.pdf",
        "bm25_query": "HKPhA-2018-04432 registration",
        "extracted_value": "HKPhA-2018-04432",
        "expected_value": "HKPhA-2018-04432",
        "status": "verified",
        "fallback_box": {"x": 20.0, "y": 30.0, "width": 35.0, "height": 4.0},
    },
    {
        "id": "pt-008",
        "category": "Qualification",
        "label": "Pharmacist Cert Expiry",
        "doc_id": "doc-002",
        "doc_filename": "pharmacist_qualification_cert.pdf",
        "bm25_query": "expiry 2026 certificate valid",
        "extracted_value": "2026-12-31",
        "expected_value": "2026-12-31",
        "status": "verified",
        "fallback_box": {"x": 20.0, "y": 38.0, "width": 28.0, "height": 4.0},
    },
    {
        "id": "pt-009",
        "category": "Qualification",
        "label": "Licence Type Applied",
        "doc_id": "doc-002",
        "doc_filename": "pharmacist_qualification_cert.pdf",
        "bm25_query": "Pharmaceutical Wholesale Dealer Licence",
        "extracted_value": "Pharmaceutical Wholesale Dealer Licence",
        "expected_value": "Pharmaceutical Wholesale Dealer Licence",
        "status": "verified",
        "fallback_box": {"x": 14.0, "y": 15.0, "width": 60.0, "height": 4.0},
    },
    # Contract
    {
        "id": "pt-010",
        "category": "Contract",
        "label": "Supplier Name",
        "doc_id": "doc-003",
        "doc_filename": "supplier_contract_sinopharm.pdf",
        "bm25_query": "Sinopharm HK Medical Development Co",
        "extracted_value": "Sinopharm HK Distribution Co., Ltd.",
        "expected_value": "Sinopharm HK Distribution Co., Ltd.",
        "status": "verified",
        "fallback_box": {"x": 12.1, "y": 41.7, "width": 37.8, "height": 4.6},
    },
    {
        "id": "pt-011",
        "category": "Contract",
        "label": "Contract Start Date",
        "doc_id": "doc-003",
        "doc_filename": "supplier_contract_sinopharm.pdf",
        "bm25_query": "1 January 2024",
        "extracted_value": "2024-01-01",
        "expected_value": "2024-01-01",
        "status": "verified",
        "fallback_box": {"x": 39.9, "y": 21.3, "width": 47.0, "height": 2.7},
    },
    {
        "id": "pt-012",
        "category": "Contract",
        "label": "Product Scope",
        "doc_id": "doc-003",
        "doc_filename": "supplier_contract_sinopharm.pdf",
        "bm25_query": "Schedule 1 Drugs OTC Pharmaceuticals",
        "extracted_value": "Schedule 1 Drugs, OTC Pharmaceuticals",
        "expected_value": "Schedule 1 Drugs, OTC Pharmaceuticals",
        "status": "verified",
        "fallback_box": {"x": 14.0, "y": 18.0, "width": 55.0, "height": 4.0},
    },
    {
        "id": "pt-013",
        "category": "Contract",
        "label": "Contract Expiry Date",
        "doc_id": "doc-003",
        "doc_filename": "supplier_contract_sinopharm.pdf",
        "bm25_query": "31 December 2025",
        "extracted_value": "2025-12-31",
        "expected_value": "2026-12-31",
        "status": "mismatch",
        "risk_note": "提交合同注明效期至 2025-12-31，而系统内部记录的现行 Sinopharm 协议有效期至 2026-12-31。疑为旧版合同。",
        "fallback_box": {"x": 39.9, "y": 26.6, "width": 47.1, "height": 2.7},
    },
    {
        "id": "pt-014",
        "category": "Contract",
        "label": "Minimum Order Quantity",
        "doc_id": "doc-003",
        "doc_filename": "supplier_contract_sinopharm.pdf",
        "bm25_query": "minimum order HKD 50000",
        "extracted_value": "HKD 50,000 per order",
        "expected_value": "HKD 50,000 per order",
        "status": "verified",
        "fallback_box": {"x": 14.0, "y": 22.0, "width": 42.0, "height": 4.0},
    },
    {
        "id": "pt-015",
        "category": "Contract",
        "label": "Payment Terms",
        "doc_id": "doc-003",
        "doc_filename": "supplier_contract_sinopharm.pdf",
        "bm25_query": "invoices payable thirty 30 days",
        "extracted_value": "Net 30 days",
        "expected_value": "Net 30 days",
        "status": "verified",
        "fallback_box": {"x": 14.0, "y": 30.0, "width": 28.0, "height": 4.0},
    },
    # Pricing
    {
        "id": "pt-016",
        "category": "Pricing",
        "label": "Price Schedule Version",
        "doc_id": "doc-004",
        "doc_filename": "product_price_list_2024.pdf",
        "bm25_query": "v2024-Q3 price schedule version",
        "extracted_value": "v2024-Q3",
        "expected_value": "v2024-Q3",
        "status": "verified",
        "fallback_box": {"x": 62.0, "y": 8.0, "width": 22.0, "height": 4.0},
    },
    {
        "id": "pt-017",
        "category": "Pricing",
        "label": "Avg. Unit Price — Category A",
        "doc_id": "doc-004",
        "doc_filename": "product_price_list_2024.pdf",
        "bm25_query": "128.00 unit price",
        "extracted_value": "HKD 128.50",
        "expected_value": "HKD 128.50",
        "status": "verified",
        "fallback_box": {"x": 74.3, "y": 33.7, "width": 10.9, "height": 2.8},
    },
    {
        "id": "pt-018",
        "category": "Pricing",
        "label": "Price Schedule Currency Denomination",
        "doc_id": "doc-004",
        "doc_filename": "product_price_list_2024.pdf",
        "bm25_query": "CURRENCY RMB Ren Min Bi",
        "extracted_value": "RMB (人民幣)",
        "expected_value": "HKD (港元)",
        "status": "risk",
        "risk_note": "价格表表头（表格区域）标注货币为 RMB (人民幣)，但所有价格明显以港元计价。疑从大陆对应文件复制未更新表头。",
        "fallback_box": {"x": 10.3, "y": 14.2, "width": 79.6, "height": 1.6},
    },
    # Technical
    {
        "id": "pt-019",
        "category": "Technical",
        "label": "ISO 13485 Certificate No.",
        "doc_id": "doc-005",
        "doc_filename": "cold_chain_certificate_iso.pdf",
        "bm25_query": "ISO-HK-2021-13485-0047 certificate",
        "extracted_value": "ISO-HK-2021-13485-0047",
        "expected_value": "ISO-HK-2021-13485-0047",
        "status": "verified",
        "fallback_box": {"x": 20.0, "y": 25.0, "width": 40.0, "height": 4.0},
    },
    {
        "id": "pt-020",
        "category": "Technical",
        "label": "Cold Chain Cert Expiry",
        "doc_id": "doc-005",
        "doc_filename": "cold_chain_certificate_iso.pdf",
        "bm25_query": "2025-06-30 expiry cold chain",
        "extracted_value": "2025-06-30",
        "expected_value": "2025-06-30",
        "status": "verified",
        "fallback_box": {"x": 20.0, "y": 33.0, "width": 28.0, "height": 4.0},
    },
    {
        "id": "pt-021",
        "category": "Technical",
        "label": "Storage Temperature Range",
        "doc_id": "doc-005",
        "doc_filename": "cold_chain_certificate_iso.pdf",
        "bm25_query": "2 8 degrees celsius refrigerated storage",
        "extracted_value": "2°C – 8°C (refrigerated)",
        "expected_value": "2°C – 8°C (refrigerated)",
        "status": "verified",
        "fallback_box": {"x": 16.0, "y": 22.0, "width": 40.0, "height": 4.0},
    },
    # Business
    {
        "id": "pt-022",
        "category": "Business",
        "label": "Audited Annual Turnover (FY2023)",
        "doc_id": "doc-006",
        "doc_filename": "company_audited_accounts_2023.pdf",
        "bm25_query": "18400000 annual turnover FY2023",
        "extracted_value": "HKD 18,400,000",
        "expected_value": "HKD 18,400,000",
        "status": "verified",
        "fallback_box": {"x": 60.0, "y": 35.0, "width": 22.0, "height": 4.0},
    },
    {
        "id": "pt-023",
        "category": "Business",
        "label": "Number of Full-Time Employees",
        "doc_id": "doc-006",
        "doc_filename": "company_audited_accounts_2023.pdf",
        "bm25_query": "24 full-time employees headcount",
        "extracted_value": "24",
        "expected_value": "24",
        "status": "verified",
        "fallback_box": {"x": 40.0, "y": 28.0, "width": 12.0, "height": 4.0},
    },
]

RULE_BY_ID: dict[str, dict] = {r["id"]: r for r in FIELD_RULES}
